{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funfunfunny",
    "module": "ClassGuard",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "ClassGuard-1.0.0.jar",
          "url": "ClassGuard-1.0.0.jar",
          "size": 40263,
          "sha512": "1ea3892b173f5ce1b5218afb7a6cb4cc9c7fd900e6a587f86b18310eced3872971fa44fa1cfd39c9a24107701a04a36ecad05689bc95845e3d5e08a2b548f414",
          "sha256": "55f263f8344b7515874c94ad162c4ae9c213e2c20d2f73b58d4c90a1b05a20c4",
          "sha1": "12e54750481ae9876af27251be6ac968dddc31d6",
          "md5": "b2dcb3cef19c2f44d3a79b3cf3de6c62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "3.0.9"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "ClassGuard-1.0.0.jar",
          "url": "ClassGuard-1.0.0.jar",
          "size": 40263,
          "sha512": "1ea3892b173f5ce1b5218afb7a6cb4cc9c7fd900e6a587f86b18310eced3872971fa44fa1cfd39c9a24107701a04a36ecad05689bc95845e3d5e08a2b548f414",
          "sha256": "55f263f8344b7515874c94ad162c4ae9c213e2c20d2f73b58d4c90a1b05a20c4",
          "sha1": "12e54750481ae9876af27251be6ac968dddc31d6",
          "md5": "b2dcb3cef19c2f44d3a79b3cf3de6c62"
        }
      ]
    }
  ]
}
